name = "自动更新的GTNL2.9_Java25_Prism安装包"
author = "Psi"
version = "20260615"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b2c1c4e02f00934f779471aa6c1d0aa1d22c4211c0f1400053c09619a34150"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
no-internal-hashes = true
